version: "3.7"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pi2user
      POSTGRES_PASSWORD: pi2pass
      POSTGRES_DB: irrigation_app
      TZ: 'America/Sao_Paulo'
      PGDATA: /data/postgres
    volumes:
       - postgres_app:/data/postgres
    # volumes:
    #   - ./pi2pgdata:/docker-entrypoint-initdb.d
  dbtest:
    image: postgres:13.2-alpine
    ports:
      - 5442:5442
    environment:
      POSTGRES_USER: pi2usertest
      POSTGRES_PASSWORD: pi2passtest
      POSTGRES_DB: irrigation_app_test
      TZ: 'America/Sao_Paulo'
      PGDATA: /data/postgres_test
    volumes:
       - postgres_app_test:/data/postgres_test
    command: -p 5442

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - 3000:80

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    volumes:
      - ./backend/api:/backend/src/api
      - ./backend/mapping:/backend/src/mapping
      - ./backend/tests:/backend/src/tests
    ports:
      - 5000:5000
    depends_on:
      - db

volumes:
  postgres_app:
  postgres_app_test: