version: '3.7'
services:
  db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pi2user
      POSTGRES_PASSWORD: pi2pass
      PGDATA: /data/postgres
    volumes:
      - pi2pgdata:/data/postgres

volumes:
  pi2pgdata: