version: "3.7"
services:
  db:
    image: postgres:13.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: pi2user
      POSTGRES_PASSWORD: pi2pass
    volumes:
      - ./pi2pgdata:/docker-entrypoint-initdb.d

  frontend:
    build:
      dockerfile: ./Dockerfile
      context: ./frontend
    volumes:
      - ./frontend/public:/frontend/public
      - ./frontend/src:/frontend/src
    ports:
      - 3000:80

  backend:
    build:
      dockerfile: ./Dockerfile
      context: ./backend
    volumes:
      - ./backend/api:/backend/src/api
      - ./backend/mapping:/backend/src/mapping
    ports:
      - 5000:5000
    depends_on:
      - db